@startuml
skinparam actor {
    BackgroundColor #cce5ff
    BorderColor #36393d
}
skinparam boundary {
    BackgroundColor #cce5ff
    BorderColor #36393d
}
skinparam control {
    BackgroundColor #cce5ff
    BorderColor #36393d
}
skinparam entity {
    BackgroundColor #cce5ff
    BorderColor #36393d
}
skinparam database {
    BackgroundColor #cce5ff
    BorderColor #36393d
}
skinparam lifeline {
    BackgroundColor #cce5ff
    BorderColor #36393d
}
skinparam participant {
    BackgroundColor #cce5ff
    BorderColor #36393d
}


actor User as A
boundary "Review Page" as B
control "ReviewController" as C
participant ":ReviewService" as S
participant ":ContractService" as CS
participant ":ReviewRepository" as R
database "Database" as DB


A -> B: 1. Submit Review Information (contractId, request)
activate B
activate A 

' Sửa đổi: Đưa bước Check Valid về Review Page (Client-side)
B -> B: 2. Check valid
activate B 
deactivate B

alt Input is invalid
    B -> A: 2.1 Display Error Message
else Input is valid
    B -> C: 4. Call POST /api/Review/{contractId}
    activate C 
    C -> S: 5. Add(userId, contractId, request) 
    activate S 
    S -> CS: 6. GetContractId(contractId)
    activate CS  
    CS -> DB: 6.2 Query Contract Details
    activate DB  
    DB --> CS: 6.3 Return Contract Data
    deactivate DB 

    CS --> S: 7. Return Contract Details 
    deactivate CS 
    S -> S: 8. Check contract deadline passed
    alt Contract deadline passed
        S -> C: 9. Return False

        C -> B: 9.1 Return Error Response ' C trả lỗi về B     
        B -> A: 9.2 Display Error Message ' B hiển thị lỗi cho User    
    else Deadline is valid
        S -> R: 10. Add(review) 
        activate R
        R -> DB: 11. Insert review 
        activate DB
        DB --> R: 12. Success
        deactivate DB
        R --> S: 13. Return success
        deactivate R
        S -> C: 14. Return "Created Successfully"
        deactivate S
    end
    C -> B: 15. Return Response
 deactivate C
    B -> A: 16. Display Success
    deactivate S
    deactivate C
    deactivate B
end
 deactivate A
@enduml