// <auto-generated />
using System;
using AmenityAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmenityAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmenityAPI.Models.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<string>("AmenityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AmenityId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            AmenityName = "WiFi",
                            OwnerId = new Guid("e8447baa-b99d-41ab-a0d7-ddaee80e2ff3")
                        },
                        new
                        {
                            AmenityId = 2,
                            AmenityName = "Air Conditioning",
                            OwnerId = new Guid("e8447baa-b99d-41ab-a0d7-ddaee80e2ff3")
                        },
                        new
                        {
                            AmenityId = 3,
                            AmenityName = "Heating",
                            OwnerId = new Guid("5b8d129c-414d-4035-9c42-d38d733c8305")
                        },
                        new
                        {
                            AmenityId = 4,
                            AmenityName = "Parking",
                            OwnerId = new Guid("5b8d129c-414d-4035-9c42-d38d733c8305")
                        },
                        new
                        {
                            AmenityId = 5,
                            AmenityName = "Laundry",
                            OwnerId = new Guid("5b8d129c-414d-4035-9c42-d38d733c8305")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
